# Generated by Django 5.2 on 2025-04-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='tracking/avatar/default.jpg', max_length=255),
        ),
    ]
